### ISSUE TITLE
Stun safe addition to script?

### ISSUE THREAD

**Issue by trickdaemon** [HxxxxxS/PsiloShift#1]
Hey man, really love the addon and have used it since I found your post on it a couple weeks ago.

There's been an update to the script that prevents it from running while stunned, is there any way you could add this to the functions?

Thank you for your time <3

**Comment by HxxxxxS** [comment]
Fixed by 8438dba83fa123b608d20aa3b298810efb8350b9

Download new version at https://github.com/HxxxxxS/PsiloShift/releases/tag/1.1.0

**Comment by trickdaemon** [comment]
You're a god, thanks!!
